### ISSUE TITLE
This is deprecated, use "new SwaggerClient" instead.  

### ISSUE THREAD

**Issue by molinto** [taxamo/taxamo-nodejs-example#2]
Getting this error on node app.js:
This is deprecated, use "new SwaggerClient" instead.

**Comment by tlipski** [comment]
I would say this was a warning, but it seems that swagger-client 2.1.1 was released recently (https://github.com/swagger-api/swagger-js/releases/tag/v2.1.1) and it wasn't working the same way as 2.1.x versions that were used for testing. I have lowered the dependency to 2.0.x allowing to run the example. I will also file an issue to raise the dependency version to 2.1.x and check if it works properly since the stable version has been released.
